### ISSUE TITLE
Build binary wheels for Linux and macOS

### ISSUE THREAD

**Issue by lpsinger** [astropy/reproject#152]
It would be really nice to have pre-built binary wheels for Linux and macOS using auditwheel and delocate.

**Comment by astrofrog** [comment]
I've asked @matthew-brett about this by email

**Comment by astrofrog** [comment]
There are now wheels:

https://pypi.org/project/reproject/#files

These are built in https://github.com/astropy/wheel-forge

**Comment by lpsinger** [comment]
Cool, thank you!
