### ISSUE TITLE
reproject_from_healpix fails with IndexError

### ISSUE THREAD

**Issue by shulevski** [astropy/reproject#153]
All of the examples given at:[]( https://reproject.readthedocs.io/en/stable/healpix.html) fail. Upon execution, I get multiple

 > Invalid ring index: 

messages, and then an error message:

> in interpolate_bilinear_lonlat(lon, lat, values, order)
    411     nside = npix_to_nside(values.shape[0])
    412     indices, weights = bilinear_interpolation_weights(lon, lat, nside, order=order)
--> 413     values = values[indices]
    414     # At this point values has shape (N, M) where both N and M might be several
    415     # dimensions, and weights has shape (N,), so we need to transpose in order
IndexError: index -137438949376 is out of bounds for axis 0 with size 49152

**Comment by astrofrog** [comment]
@shulevski - would it be possible for you to provide the input image you used and the reproject function call? (basically a minimal script would be helpful to debug this). Thanks!

**Comment by shulevski** [comment]
The image is from the online tutorial, so if you execute:

`from astropy.utils.data import get_pkg_data_filename
filename_ligo = get_pkg_data_filename('allsky/ligo_simulated.fits.gz')
`
you will have it in the variable.

**Comment by cdeil** [comment]
This bug might be fixed via this fix that just landed in astropy-healpix master:
https://github.com/astropy/astropy-healpix/pull/106

**Comment by astrofrog** [comment]
@shulevski - it looks like this might be fixed, but let me know if it still doesn't work with the latest version of astropy-healpix and reproject!
