### ISSUE TITLE
Add support for reprojecting images with SIP

### ISSUE THREAD

**Issue by pboley** [astropy/reproject#171]
When reprojecting images with non-linear distortions described by SIP polynomials (https://fits.gsfc.nasa.gov/registry/sip.html) this information seems to be ignored. If it is not planned to include support for SIP, this could at least be mentioned explicitly in the manual.

**Comment by astrofrog** [comment]
I would like to make sure we support files with SIP - this is an oversight.

**Comment by astrofrog** [comment]
This is now done by default in the latest developer version. Feel free to re-open the issue if you find that this is not the case!
