### ISSUE TITLE
reproject_interp() is giving me an error message I can't parse

### ISSUE THREAD

**Issue by jsbridge** [astropy/reproject#173]
Hi, I'm doing a simple (I thought) reprojection of two HST images that are slightly misaligned from each other. I've done this before with no issues. Now, however, when I run this step: 

array, footprint = reproject_interp(hdu2, hdu1.header)

I get "ValueError: Length of shape_out should match number of dimensions in wcs_out."

The only other thing I get is a warning that says "WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]."

I have no idea if these two things are related, but I can't figure out what either of them mean. If you have any insight into what could be going wrong, that would be great.

**Comment by astrofrog** [comment]
@jsbridge - can you print out ``hdu1.data.shape`` and ``hdu2.data.shape``? Thanks!

**Comment by jsbridge** [comment]
Yes, the dimensions of the science frames from each FITS file are (1943, 1845) and (1954, 1861).

**Comment by jsbridge** [comment]
Hi, just checking in again to see if there's anything else I should try?

**Comment by astrofrog** [comment]
@jsbridge - sorry for the delay, if you are still running into issues, could you print ``hdu1.header``?

**Comment by astrofrog** [comment]
@jsbridge - can you try the latest version of reproject (0.7) and see if you are still having issues? If so, can you send input files and an example script to thomas.robitaille@gmail.com? Thanks!
