### ISSUE TITLE
Tagging new release

### ISSUE THREAD

**Issue by bsipocz** [astropy/reproject#175]
@astrofrog - reproject will start to raise DeprecationWarnings when used with astropy v3.2.

Given it's a coordinated package, I think it would be beneficial to avoid this by doing a new release now either calling it 0.4.1 or 0.5 rather than waiting longer to get more features in.

**Comment by astrofrog** [comment]
[reproject 0.5](https://pypi.org/project/reproject/0.5/) was released on June 13, so closing :)
