### ISSUE TITLE
Add support for NDData

### ISSUE THREAD

**Issue by Cadair** [astropy/reproject#177]
Given most of the high level functions accept a data, wcs pair and a wcs array shape pair it would be awesome if you could pass two NDData objects into reproject. I am thinking:

```python
reproject_interp(nddata_in, nddata_out)
```
where instead of `array_shape` you are actually passing in an array you want the reproject function to write into (i.e. `out=` kwargs in numpy functions).

**Comment by astrofrog** [comment]
Done in https://github.com/astropy/reproject/pull/198
