### ISSUE TITLE
Possible bug in reproject_interp header reading

### ISSUE THREAD

**Issue by prajwel** [astropy/reproject#185]
Hi, 

when running the command
`array, footprint = reproject_interp(vlass_hdu, alma_hdu[0].header)`
I get the following warnings and an image filled with Nan. 

> WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to  -107.618000 from OBSGEO-[XYZ].
> Set OBSGEO-B to    34.078827 from OBSGEO-[XYZ].
> Set OBSGEO-H to     2115.607 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC01_01 = 1.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC02_01 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC03_01 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC04_01 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC01_02 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC02_02 = 1.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC03_02 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC04_02 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC01_03 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC02_03 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC03_03 = 1.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC04_03 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC01_04 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC02_04 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC03_04 = 0.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: PC04_04 = 1.000000000000E+00 
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -67.754929 from OBSGEO-[XYZ].
> Set OBSGEO-B to   -23.022886 from OBSGEO-[XYZ].
> Set OBSGEO-H to     5053.796 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]

I saw a similar issue here https://github.com/radio-astro-tools/spectral-cube/issues/280

Thank you for any help!

**Comment by astrofrog** [comment]
Can you send the data file and the script you are using to reproject it to thomas.robitaille@gmail.com - thanks!

**Comment by prajwel** [comment]
I have sent it. @astrofrog

**Comment by astrofrog** [comment]
@prajwel - this is not technically a bug, but is due to the fact that both your datasets are 4D cubes, which don't overlap in frequency space. There are two possible workarounds:

* Either you can set the frequencies of the cubes to match by doing:

vlass_hdu[0].header['CRVAL3'] = alma_hdu[0].header['CRVAL3']

* Or you can slice the FITS files and the WCS so that they are real 2D images

**Comment by prajwel** [comment]
Thank you!
