### ISSUE TITLE
Algorithms in the "reproject_exact" module?

### ISSUE THREAD

**Issue by Kein-Cary** [astropy/reproject#196]
Is there an article recommended (somthing about the algorithms in the "reproject_exact" module)? I want to know how the "reproject_exact" can make a "flux-conserving" image projection?

**Comment by astrofrog** [comment]
You can find out more about the Montage algorithm (used in ``reproject_exact``) here:

http://montage.ipac.caltech.edu/docs/algorithms.html

We should make this clearer in the docs.

**Comment by astrofrog** [comment]
I've now linked to the algorithm page at https://reproject.readthedocs.io/en/latest/celestial.html#spherical-polygon-intersection
