### ISSUE TITLE
Update conda release to 0.6?

### ISSUE THREAD

**Issue by AlistairSymonds** [astropy/reproject#206]
Hi there, I've got (what is hopefully) a very small request, could the version on conda be updated to 0.6? It seems the pip version is up to date but conda isn't, and having this just makes sharing code utilising the new features that little bit easier.

Doing:

conda install -c astropy reproject

and checking on

https://anaconda.org/astropy/reproject

All return 0.51 as the latest

**Comment by astrofrog** [comment]
@AlistairSymonds - this should be fixed now, can you check?
