### ISSUE TITLE
reproject_exact() returns `weights` unexpectedly while `parallel` is False

### ISSUE THREAD

**Issue by izkgao** [astropy/reproject#212]
When using `reproject_exact()`, I found that if I pass `parallel=False, return_footprint=True` to it, it will still return the footprint.

**Comment by wdobbels** [comment]
Just ran into the same issue with v0.6, but it seems to be fixed in 506c95684c36683ec8e7e1250586c768465574c2 (ready to be released in 0.7).

**Comment by astrofrog** [comment]
Indeed this is fixed in v0.7!
