### ISSUE TITLE
Reproject >=0.7 specifies that it's not compatible with python 3.7 on astropy conda channel

### ISSUE THREAD

**Issue by emirkmo** [astropy/reproject#238]
So if you are running 3.7 or later, reproject can only be installed up to 0.6, which makes it incompatible with Astropy >=4.0 due to the known bug fixed in 0.7.

**Comment by Cadair** [comment]
Where are you running into this, 0.7 in the [setup.cfg](https://github.com/astropy/reproject/blob/v0.7.x/setup.cfg#L17) and on pypi show Python >= 3.6.

**Comment by emirkmo** [comment]
This is very strange but it seems to be a Conda issue in the astropy channel. And now I see that the version on pypi is working fine. I did try just using pip again after removing all versions and it installed fine. Did not need --no-deps. Perhaps something very strange happened on my end so I moved to a clean install.

Conda, however, still gives the following error using:

conda install -c astropy reproject==0.7

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - reproject==0.7 -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7

This is using Conda 4.8.3

**Comment by Cadair** [comment]
@mwcraig Do you have any ideas on this?

**Comment by mwcraig** [comment]
Can take a look this afternoon after 2100UTC.

**Comment by pllim** [comment]
astropy has since dropped Python 3.7, so this is no longer relevant.
