### ISSUE TITLE
Please issue a new release

### ISSUE THREAD

**Issue by pkgw** [astropy/reproject#253]
WWT's tiled FITS support is coming together, and to properly support tiling collections of several FITS files, it would be really great to get a new release that contains the change contributed in #242. Thanks!

**Comment by astrofrog** [comment]
Sounds good, I'll add it to my list for the coming week

**Comment by pkgw** [comment]
Thanks, Tom! Let me know if I can help out with any of the mechanics — looks like some of the CI scripts might need updating?

**Comment by pkgw** [comment]
This was done a while ago, thanks!
