### ISSUE TITLE
TST: Unpin coverage when timeout problem resolved upstream

### ISSUE THREAD

**Issue by pllim** [astropy/reproject#280]
Revert #277 when coverage timeout problem is fixed upstream. Still see timeout with 6.3.1.

**Comment by astrofrog** [comment]
Thanks! Maybe we should update the tox config to use the ci helpers pinning?

**Comment by pllim** [comment]
I don't think we have to pin project wide? Only coverage 6.3.x + multiprocessing tests seem to be affected.

**Comment by astrofrog** [comment]
Ah I see, yes then pinning here is fine

**Comment by pllim** [comment]
Maybe we can revisit soon: https://github.com/nedbat/coveragepy/issues/1310#issuecomment-1129894701
