### ISSUE TITLE
Support for common use case: reprojecting multiple images with the same original WCS 

### ISSUE THREAD

**Issue by entaylor** [astropy/reproject#296]
I am in the midst of a very large undertaking, with many 100s of 1000s of images, each with its own variance map.

Currently i am reprojecting the image and variance maps separately.  This means i am duplicating lots of coordinate transformation computations, where in principle i could apply the pixel-to-pixel mapping from one image directly to the other.

Given that transforming images and error/variance/weight maps is a common operation, is there a straightforward way to make it possible feed multiple images into reproject?  Especially in conjunction with issue #229 this could give of order 50-75% reduction in run time for this phase of my code.

**Comment by Cadair** [comment]
Just to clarify, you have the same input and output WCS for all these reproject operations or just the same input WCS?

**Comment by entaylor** [comment]
Every image has an associated error map, so two arrays with the same geometry and WCS.  Then i project these to a different final WCS.  I have many images all with their own WCS, but each has its associated error map.  

Maybe it's easier in pseudo code.  What i do now is something like:
```
for (image, variance, wcs_in) in get_lots_of_data :
    img_reproj = reproject( (image, wcs_in), wcs_out)
    var_reproj = reproject( (variance, wcs_in), wcs_out)
```

What i would like to do is something like:
```
for (image, variance, wcs_in) in get_lots_of_data :
    img_reproj, var_reproj = reproject( ((image, variance), wcs_in), wcs_out)
```

The idea is just to reduce the number of repeated WCS transformations.

**Comment by entaylor** [comment]
Gently bumping this for visibility.  How easy would it be to cache the pixel-to-pixel mapping to apply to multiple input images (with a common input WCS) being projected to the same output WCS?

**Comment by Cadair** [comment]
One thing you could try is putting the `lru_cache` decorator on this function: https://github.com/astropy/reproject/blob/3cfc7a8f402789d338eb2379b1ba1b7b2e265738/reproject/wcs_utils.py#L15

You would probably want to tune the size of the cache (maybe to only cache the last call) so that it didn't eat a *lot* of ram. It would be good to know if it worked and then we could think about how to integrate it and make it configurable.

**Comment by svank** [comment]
I'm also interested in this feature and can help with the implementation, especially for the adaptive algorithm.

The `lru_cache` decorator does seem like the easiest implementation, but keeping even just the single most recent transform in ram for the rest of the script or notebook's runtime seems unfortunate, even if inexpensive (and for adaptive, if centered jacobians are used, the *three* most recent calls would have to be cached).

It might be cleaner to implement an API like @entaylor suggested of
```
reproject(([input_data_1, input_data_2, input_data_3], input_wcs), ouput_wcs, output_shape)
```

I think this should be relatively easy to implement. It looks like both the adaptive and exact algorithms follow a pattern in their `core.py` of computing the coordinate mapping for all pixels, and then doing the resampling, so it should be easy to add a loop over input data arrays once the WCS work is done. And in the adaptive algorithm, the WCS work is triggered from cython, but the input data array values are only accessed in the innermost point of the cython loop (and in a couple edge cases), so it should be easy to add a loop there over multiple input data arrays.

**Comment by entaylor** [comment]
Gently bumping this for visibility.  @svank are you still keen to look into this and is there any way i can help?  I can be good moral support.  : )

**Comment by svank** [comment]
@entaylor Yes, I'm still interested---I have people down the hall who are also interested in this feature. I think I was waiting to see if there were any other thoughts on the API and I've now become Busy, but I could probably do this a month or two from now.

**Comment by astrofrog** [comment]
Done in #332
