### ISSUE TITLE
Find a way to avoid customizing map_coordinates

### ISSUE THREAD

**Issue by astrofrog** [astropy/reproject#342]
We have a wrapper of map_coordinates in array_utils.py which pads the array before being called - however this causes the input array to be loaded into memory, whereas if we didn't do this map_coordinates from scipy could deal well with memory-mapped arrays.

We should explore this again and see if we can avoid having to include this wrapper.

**Comment by Cadair** [comment]
Also presumably dropping the wrapper would help with the future use of any dask-image variant of map_coordinates?

**Comment by astrofrog** [comment]
Indeed!

**Comment by astrofrog** [comment]
We're going to have to use the wrapper for the foreseeable future as it also now handles the fact that the default ``map_coordinates`` loads the whole array for big-endian data. However, we no longer have memory issues in ours, so we can close this now.
