### ISSUE TITLE
reproject_interp with parallel=True ignores order='nearest-neighbor'? 

### ISSUE THREAD

**Issue by ashleythomasbarnes** [astropy/reproject#384]
`reproject.__version__ = '0.11.0'`

I noticed that: 

`reproject_interp(hdu, header, order='nearest-neighbor', parallel=True)`

and 

`reproject_interp(hdu, header, order='nearest-neighbor')`

give different results. It appears the former ignores the `order` kwarg and returns some interpolation. This is most obvious when regridding a low resolution mask to a much higher resolution. Is this a known issue?

**Comment by astrofrog** [comment]
Thanks for the report! Yes I noticed this recently and will fix shortly.

**Comment by astrofrog** [comment]
@ashleythomasbarnes this should be fixed by https://github.com/astropy/reproject/pull/374. I hope to release a new version soon but in the mean time let me know if you are able to try out the latest developer version and whether it fixes things.
