### ISSUE TITLE
Upload wheels for Python 3.12

### ISSUE THREAD

**Issue by dstansby** [astropy/reproject#398]

**Comment by astrofrog** [comment]
Should happen now that #405 is merged - will tag a release shortly

**Comment by dstansby** [comment]
Looks like the wheels haven't been uploaded yet: https://pypi.org/project/reproject/#files

**Comment by dstansby** [comment]
Looks like this is just because one of the wheel builds failed on a connection error. Restarting the GH actions pipeline should fix? https://github.com/astropy/reproject/actions/runs/6627264542/job/18003961859
