### ISSUE TITLE
BLD: build is currently broken on Python 3.8

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/reproject#421]
#415 broke test jobs on Python 3.8 (numpy 1.25 requires Python 3.9 or newer). There are two possible approaches to fix this:
- use `oldest-supported-numpy` on Python 3.8 instead (keep using `numpy>1.25` for other versions)
- drop support for Python 3.8

I'm happy to do the work either way, just please let me know what's preferred here! Ping @astrofrog

**Comment by astrofrog** [comment]
This is already done in https://github.com/astropy/reproject/pull/411

**Comment by neutrinoceros** [comment]
Awesome. @astrofrog please let me know if you need (or would like) my review. I can make some time for it tomorrow !

**Comment by astrofrog** [comment]
@neutrinoceros - feel free to review!
