### ISSUE TITLE
Implement a function that returns a north-aligned header or WCS

### ISSUE THREAD

**Issue by astrofrog** [astropy/reproject#79]
One common use case is for people to reproject an image so it's aligned with the celestial north. We should provide a function that given a header or WCS returns a header or WCS that is aligned with the north for that coordinate system. It would also be great to be able to specify which coordinate system use (e.g. ICRS north, Galactic north, etc.).

**Comment by cdeil** [comment]
There's also the cases of images where the longitude increases to the right (a positive CDELT2), whereas in most astronomical images it increases to the right.

Example:  http://fermi.gsfc.nasa.gov/ssc/data/analysis/software/aux/gll_iem_v02.fit

It would be great to have a utility function somewhere like [numpy.fliplr](http://docs.scipy.org/doc/numpy/reference/generated/numpy.fliplr.html) that flips the array and a header or wcs object.

@astrofrog I guess this should be separate from what you're proposing here. Do you think this belongs in `reproject` or  `astropy.nddata.utils` or `astropy.wcs.utils` or ???

**Comment by astrofrog** [comment]
@cdeil - it depends: for functions that take a WCS and return a WCS then astropy.wcs.utils would be appropriate. However, one thing that is annoying is that WCS does not contain information on image size, so we'd also want a utility that finds the optimal final image size.

**Comment by astrofrog** [comment]
This was implemented in https://github.com/astropy/reproject/pull/136
